### ISSUE TITLE
[Question] is the LabelIndex correspond to supervoxel or the agglomerated label map?

### ISSUE THREAD

**Issue by jingpengw** [janelia-flyem/neuclease#10]
Currently, I am trying to construct the LabelIndex based on the supervoxels. I am not sure whether it is correct or not. 
Based on the name, it sounds like I should use the agglomerated label map rather than supervoxels to count the number of voxels?

**Comment by stuarteberg** [comment]
The labelindex stores the block locations that the agglomerated body touches, along with the supervoxels (for that body only) which reside in each block, along with the voxel counts for each of those supervoxels within that block.

DVID's 'native' format for LabelIndexes is based on a protobuf structure, but for interactive manipulation, `neuclease` will convert it to a `namedtuple` containing a DataFrame for the block table.

Here's an example from the hemibrain:

```python
In [32]: from neuclease.dvid import fetch_labelindex
    ...:
    ...: hemi_seg = ('https://hemibrain-dvid.janelia.org', '31597d', 'segmentation')
    ...: index_data = fetch_labelindex(*hemi_seg, 571778433, format='pandas')
    ...: index_data.blocks.head()
Out[32]:
       z      y      x          sv   count
0   9728  14080  14912   693828663     236
1   9920  12672  14656   692801308    3444
2  20032  33728  16832   973488141  144202
3  20416  32704  25024  1328254933  169773
4   4864  19008  21312   325221508  247904
```

Large supervoxels might span across multiple blocks, so they'll appear in more than one row of that table (with a different voxel count each time).  Also,  if a single block contains multiple supervoxels (from the same agglomerated body), then that block's `zyx` coordinates will appear multiple times (one for each supervoxel ID).

But each supervoxel should only be referenced once per block location:

```python
In [33]: assert not index_data.blocks.duplicated([*'zyx', 'sv']).any()
```

You can convert from that format back to the protobuf version via `create_labelindex()`:

```python
In [34]: from neuclease.dvid import create_labelindex, PandasLabelIndex
    ...: assert isinstance(index_data, PandasLabelIndex)
    ...: protobuf_index = create_labelindex(index_data)
```

**Comment by jingpengw** [comment]
thanks a lot for the detailed explanation and example code! that is super helpful!

So I can post the label index distributedly for each chunk/block, right?
