### ISSUE TITLE
[question] How to delete all the label indices and label map?

### ISSUE THREAD

**Issue by jingpengw** [janelia-flyem/neuclease#11]
I ingested some label indices that are not correct. Creating a new repo and reingest the supervoxels will take a long time. Is that possible to delete all the label indices and label map?

**Comment by stuarteberg** [comment]
>according to the comments, I can post an empty label index to delete all of them?

No, you can only delete indices for an explicitly provided list of bodies, as is done in `delete_labelindices()`.

As far as I can tell, the [REST API](https://hemibrain-dvid.janelia.org/api/help/labelmap) doesn't offer a way to delete all label indices for the whole instance.

You might want to open a new issue on the [dvid repository](https://github.com/janelia-flyem/dvid/issues) to request that feature.

**Comment by jingpengw** [comment]
I just found a related issue in dvid repo:
https://github.com/janelia-flyem/dvid/issues/341

**Comment by jingpengw** [comment]
@stuarteberg I am trying to use the `delete_labelindices`, but just found that this is added recently and is not in the conda environment. Could you please help to update the conda environment?

**Comment by jingpengw** [comment]
I manually added this function to my local nuclease code and works for now. This is pretty hacky though.

**Comment by stuarteberg** [comment]
This ought to work:

```bash
conda install -c flyem-forge 'neuclease>=0.4.post429'
```

**Comment by jingpengw** [comment]
thank you!
