### ISSUE TITLE
[question] does the fetched supervoxel include the splitted results in NeuTu?

### ISSUE THREAD

**Issue by jingpengw** [janelia-flyem/neuclease#17]
It seems that one supervoxel can be mapped to multiple label.
If a proofreader split a supervoxel in NeuTu, does the supervoxel got updated in DVID?
If not, how can I fetch the splitted supervoxel?

**Comment by DocSavage** [comment]
A supervoxel can only be mapped to a single label at a particular time. It's possible a supervoxel will be mapped to different labels over proofreading. If a supervoxel is split, each split piece gets a unique supervoxel ID and is recorded in DVID. Did I understand your question correctly?

**Comment by jingpengw** [comment]
if I fetch the supervoxel, it will be split into two or multiple pieces?

**Comment by jingpengw** [comment]
my current issue is that the fetched supervoxel are not split and it can map to multiple labels.

**Comment by DocSavage** [comment]
You probably already know this but just to make sure we're on the same page, here's how supervoxel ops work in our framework. Supervoxels are atomic. Once ingested, they can be split in NeuTu into new supervoxels and this split can be registered with DVID. At that point the original supervoxel id is mapped to 0 (taken out of circulation) and the split supervoxels are still mapped to the same label but can then be cleaved so they get assigned to different bodies.

Could you clarify what you mean by "fetched supervoxel"?

**Comment by jingpengw** [comment]
Thank you! 

the "fetched supervoxel" means the supervoxel chunk/volume downloaded from the DVID server.
It looks like a bug on my end. The supervoxel maps to one label from the DVID server. 
This looks expected. I downloaded/fetched the supervoxel and segmentation at different times and the version does not match anymore.

I'll close it for now.
