### ISSUE TITLE
building tile locally and then post to DVID server?

### ISSUE THREAD

**Issue by jingpengw** [janelia-flyem/neuclease#8]
It seems that the post_raw or post_subvol will not build tiles locally and we have to rely on the computation of the server which is quite slow. I am wondering that is my understanding correct? If so, any plan to build tiles in local worker?

https://github.com/janelia-flyem/neuclease/blob/master/neuclease/dvid/voxels.py#L78

**Comment by stuarteberg** [comment]
Yes, that's correct.  In FlyEM, we typically build our image pyramids on a cluster, and then upload them.  If you'd like some advice for doing that, let me know.

FWIW, the code we use for ingesting grayscale data into DVID (including pyramid generation) is here:

https://github.com/janelia-flyem/flyemflows/blob/master/flyemflows/workflow/copygrayscale.py

...but it's not well documented, I'm afraid.  It relies on `dask`, and I typically run it on our compute cluster.

**Comment by jingpengw** [comment]
Thanks for the help and code guidance. Pat helped to add a feature in DVID to read Neuroglancer precomputed format in AWS S3. this feature is not necessary for now.
